name: "Install xmipp4-core with pip"
description: "Build and install xmipp4-core from source with pip"

inputs:
  ref:
    description: "Branch or tag in the xmipp4-core repo"
    required: false
  path:
    description: "Path where xmipp4-core will be downloaded and built from"
    required: false
    default: ${{ github.workspace }}/../xmipp4-core

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: gigabit-clowns/xmipp4-core
        ref: ${{ inputs.ref }}
        path: xmipp4-core
    
    - name: Move xmipp4-core outside current repository
      shell: bash
      run: mv xmipp4-core "${{ inputs.path }}"

    - name: Install project with pip
      shell: bash
      working-directory: "${{ inputs.path }}"
      run: pip install . -vvv
