name: "Install Memcheck tool"
description: "Installs the required memcheck tool for every OS."

inputs:
  only-export-path:
    description: "If set, no tool will be installed, only relevant paths will be exported without modification."
    required: false
    default: false
outputs:
  drmemory-bash:
    description: "Full path to Dr. Memory (in bash format)."
    value: ${{ steps.export-drmemory-bash.outputs.drmemory }}
  drmemory-pwsh:
    description: "Full path to Dr. Memory (in Powershell format)."
    value: ${{ steps.export-drmemory-pwsh.outputs.drmemory }}

runs:
  using: "composite"
  steps:
    - name: Install Valgrind (Linux)
      if: runner.os == 'Linux' && inputs.only-export-path == 'false'
      shell: bash
      run: |
        if which apt-get; then
          sudo apt-get update
          sudo apt-get install -y valgrind
        else
          echo "Could not find a package manager for this system"
          exit 1
        fi

    - name: Install Dr. Memory (Windows)
      if: runner.os == 'Windows' && inputs.only-export-path == 'false'
      shell: bash
      run: choco install drmemory

    - name: Export Dr. Memory path for Windows (Bash)
      id: export-drmemory-bash
      if: runner.os == 'Windows'
      shell: bash
      run: echo "drmemory=\"/c/Program Files (x86)/Dr. Memory/bin64/drmemory.exe\"" >> "$GITHUB_OUTPUT"

    - name: Export Dr. Memory path for Windows (Powershell)
      id: export-drmemory-pwsh
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $path = 'C:\Program Files (x86)\Dr. Memory\bin64\drmemory.exe'
        Add-Content -Path $env:GITHUB_OUTPUT -Value "drmemory=$path"
