name: "Run CMake tests"
description: "Runs CMake tests for every OS"

inputs:
  check-memleaks:
    description: "If set to true, test will be run checking for memory leaks."
    required: false
    default: false
  drmemory:
    description: "Full path to Dr. Memory executable"
    required: false
outputs:
  exist-memleaks:
    description: "If True, the tests run show memory leaks." 
    value: ${{ steps.run-with-memcheck.outputs.exist-memleaks }}
  memleak-test-numbers:
    description: "Numbers of the tests with memory leaks." 
    value: ${{ steps.run-with-memcheck.outputs.test-numbers }}

runs:
  using: "composite"
  steps:
    - name: Run tests without memory check (Linux)
      if: runner.os == 'Linux' && inputs.check-memleaks == 'false'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: ctest -C ${{ env.BUILD_TYPE }} -T test --rerun-failed --output-on-failure

    - name: Run tests without memory check (Windows)
      if: runner.os == 'Windows' && inputs.check-memleaks == 'false'
      working-directory: "${{ github.workspace }}/build"
      shell: cmd
      run: ctest -T test --rerun-failed --output-on-failure

    - name: Run tests without memory check (MacOS)
      if: runner.os == 'macOS' && inputs.check-memleaks == 'false'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: ctest -C ${{ env.BUILD_TYPE }} -T test --rerun-failed --output-on-failure

    - name: Run tests with memory check
      if: inputs.check-memleaks == 'true'
      id: run-with-memcheck
      uses: ./.github/composites/run-ctest/memcheck
      with:
        drmemory: ${{ inputs.drmemory }}
