name: "SonarQube scan"
description: "Runs SonarQube scan."

inputs:
  sonar-token:
    description: "SonarQube token"
    required: true
  build-artifact-name:
    description: "Name of the build artifact to download."
    required: true
  coverage-pattern:
    description: "Pattern of the artifact/s to download."
    required: false
  coverage-path:
    description: "Path where the artifact/s will be downloaded."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0 # Needed to get git blame information for SonarQube

    - uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.build-artifact-name }}
        path: ${{ github.workspace }}/build

    - uses: actions/download-artifact@v6
      if: ${{ inputs.coverage-pattern && inputs.coverage-path }}
      with:
        pattern: ${{ inputs.coverage-pattern }}
        path: ${{ inputs.coverage-path }}

    - name: Setup .NET Core # Required to execute ReportGenerator
      if: ${{ inputs.coverage-pattern && inputs.coverage-path }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.x
        dotnet-quality: 'ga'

    - name: Merge coverage reports (ReportGenerator)
      if: ${{ inputs.coverage-pattern && inputs.coverage-path }}
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: ./build/coverage-report-ubuntu-latest-gcc-g++/coverage.xml;./build/coverage-report-macos-latest-clang-clang++/coverage.xml;./build/coverage-report-windows-latest-gcc-g++/coverage.xml;./build/coverage-report-ubuntu-latest-clang-clang++/coverage.xml;./build/coverage-report-windows-latest-cl-cl/coverage.xml
        targetdir: build
        reporttypes: Cobertura
        sourcedirs: ${{ github.workspace }}
    
    - name: Rename merged coverage report
      if: ${{ inputs.coverage-pattern && inputs.coverage-path }}
      shell: bash
      run: mv ./build/Cobertura.xml ./build/coverage.xml

    # Regular scan for most events
    - name: SonarQube scan for most events
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}

    # When trigger event is workflow_dispatch, SonarQube action
    # will always treat it as main branch unless we specify the branch name
    - name: SonarQube scan for workflow_dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: SonarSource/sonarqube-scan-action@v6
      env:
          SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        args: >
          -Dsonar.branch.name=${{ github.ref_name }}
