// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include "cpp_features.hpp"

#if XMIPP4_HAS_CONSTEXPR || defined(XMIPP4_DOC_BUILD)
    #define XMIPP4_CONSTEXPR constexpr
    #define XMIPP4_CONST_CONSTEXPR constexpr
    #define XMIPP4_INLINE_CONSTEXPR constexpr
    #define XMIPP4_INLINE_CONST_CONSTEXPR constexpr
#else
    #define XMIPP4_CONSTEXPR
    #define XMIPP4_CONST_CONSTEXPR const
    #define XMIPP4_INLINE_CONSTEXPR inline
    #define XMIPP4_INLINE_CONST_CONSTEXPR inline const
#endif

#if XMIPP4_HAS_IF_CONSTEXPR
    #define XMIPP4_IF_CONSTEXPR XMIPP4_CONSTEXPR
#else
    #define XMIPP4_IF_CONSTEXPR
#endif

// C++11
#if XMIPP4_HAS_CPP11
    #define XMIPP4_CONSTEXPR_CPP11 XMIPP4_CONSTEXPR
    #define XMIPP4_CONST_CONSTEXPR_CPP11 XMIPP4_CONST_CONSTEXPR
    #define XMIPP4_INLINE_CONSTEXPR_CPP11 XMIPP4_INLINE_CONSTEXPR
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP11 XMIPP4_INLINE_CONST_CONSTEXPR

#else
    #define XMIPP4_CONSTEXPR_CPP11
    #define XMIPP4_CONST_CONSTEXPR_CPP11 const
    #define XMIPP4_INLINE_CONSTEXPR_CPP11 inline
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP11 inline const
#endif

// C++14
#if XMIPP4_HAS_CPP14
    #define XMIPP4_CONSTEXPR_CPP14 XMIPP4_CONSTEXPR
    #define XMIPP4_CONST_CONSTEXPR_CPP14 XMIPP4_CONST_CONSTEXPR
    #define XMIPP4_INLINE_CONSTEXPR_CPP14 XMIPP4_INLINE_CONSTEXPR
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP14 XMIPP4_INLINE_CONST_CONSTEXPR
#else
    #define XMIPP4_CONSTEXPR_CPP14
    #define XMIPP4_CONST_CONSTEXPR_CPP14 const
    #define XMIPP4_INLINE_CONSTEXPR_CPP14 inline
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP14 inline const
#endif

// C++17
#if XMIPP4_HAS_CPP17
    #define XMIPP4_CONSTEXPR_CPP17 XMIPP4_CONSTEXPR
    #define XMIPP4_CONST_CONSTEXPR_CPP17 XMIPP4_CONST_CONSTEXPR
    #define XMIPP4_INLINE_CONSTEXPR_CPP17 XMIPP4_INLINE_CONSTEXPR
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP17 XMIPP4_INLINE_CONST_CONSTEXPR
#else
    #define XMIPP4_CONSTEXPR_CPP17
    #define XMIPP4_CONST_CONSTEXPR_CPP17 const
    #define XMIPP4_INLINE_CONSTEXPR_CPP17 inline
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP17 inline const
#endif

// C++20
#if XMIPP4_HAS_CPP20
    #define XMIPP4_CONSTEXPR_CPP20 XMIPP4_CONSTEXPR
    #define XMIPP4_CONST_CONSTEXPR_CPP20 XMIPP4_CONST_CONSTEXPR
    #define XMIPP4_INLINE_CONSTEXPR_CPP20 XMIPP4_INLINE_CONSTEXPR
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP20 XMIPP4_INLINE_CONST_CONSTEXPR
#else
    #define XMIPP4_CONSTEXPR_CPP20
    #define XMIPP4_CONST_CONSTEXPR_CPP20 const
    #define XMIPP4_INLINE_CONSTEXPR_CPP20 inline
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP20 inline const
#endif

// C++23
#if XMIPP4_HAS_CPP23
    #define XMIPP4_CONSTEXPR_CPP23 XMIPP4_CONSTEXPR
    #define XMIPP4_CONST_CONSTEXPR_CPP23 XMIPP4_CONST_CONSTEXPR
    #define XMIPP4_INLINE_CONSTEXPR_CPP23 XMIPP4_INLINE_CONSTEXPR
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP23 XMIPP4_INLINE_CONST_CONSTEXPR
#else
    #define XMIPP4_CONSTEXPR_CPP23
    #define XMIPP4_CONST_CONSTEXPR_CPP23 const
    #define XMIPP4_INLINE_CONSTEXPR_CPP23 inline
    #define XMIPP4_INLINE_CONST_CONSTEXPR_CPP23 inline const
#endif