name: "Install Memcheck tool"
description: "Installs the required memcheck tool for every OS"

inputs:
  os:
    description: "OS the worker runs on"
    required: true

outputs:
  drmemory:
    description: "Full path to Dr. Memory executable"
    value: ${{ steps.install-drmemory.outputs.drmemory }}

runs:
  using: "composite"
  steps:
    - name: Get OS type
      uses: ./.github/composites/detect-os-type
      id: get-os-type
      with:
        os: ${{ inputs.os }}
    
    - name: test echo
      shell: bash
      run: echo "Received OS - ${{ steps.get-os-type.outputs.os_type }}"

    - name: Install Valgrind (Ubuntu)
      if: steps.get-os-type.outputs.os_type == 'debian'
      shell: bash
      run: sudo apt-get install -y valgrind

    - name: Install Dr. Memory (Windows)
      id: install-drmemory
      if: steps.get-os-type.outputs.os_type == 'windows'
      shell: bash
      run: |
        choco install drmemory
        echo "drmemory=\"/c/Program Files (x86)/Dr. Memory/bin/drmemory.exe\"" >> "$GITHUB_OUTPUT"
