name: "Install Memcheck tool"
description: "Installs the required memcheck tool for every OS"

outputs:
  drmemory:
    description: "Full path to Dr. Memory executable"
    value: ${{ steps.install-drmemory.outputs.drmemory }}

runs:
  using: "composite"
  steps:
    - name: Install Valgrind (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if which apt > /dev/null 2>&1; then
          echo "Installing valgrind from apt..."
          sudo apt-get install -y valgrind
        elif which snap > /dev/null 2>&1; then
          echo "Installing valgrind from snap..."
          sudo snap install valgrind --classic
        else
          echo "Could not find a package manager for this system"
          exit 1
        fi

    - name: Install Dr. Memory (Windows)
      id: install-drmemory
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install drmemory
        echo "drmemory=\"/c/Program Files (x86)/Dr. Memory/bin/drmemory.exe\"" >> "$GITHUB_OUTPUT"
