name: "Run test with memory checks"
description: "Runs test with memcheck for every OS"

inputs:
  os:
    description: "OS the worker runs on"
    required: true
  drmemory:
    description: "Full path to Dr. Memory executable"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run tests with memory check (Ubuntu)
      if: ${{ inputs.os }} == 'ubuntu-latest'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: ctest -C ${{ env.BUILD_TYPE }} -T memcheck --rerun-failed --output-on-failure
    
    - name: Run tests with memory check (Windows)
      if: ${{ inputs.os }} == 'windows-latest'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: ${{ inputs.drmemory }} -show_reachable -- ctest -C ${{ env.BUILD_TYPE }} --rerun-failed --output-on-failure

    - name: Run tests with memory check (MacOS)
      if: ${{ inputs.os }} == 'macos-latest'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: |
        export MallocStackLogging=1
        leaks --fullContent --atExit -- ctest -C ${{ env.BUILD_TYPE }} --rerun-failed --output-on-failure
