# File based on:
# https://github.com/pybind/cmake_example/blob/master/conda.recipe/meta.yaml
# https://scikit-build-core.readthedocs.io/en/stable/faqs.html#making-a-conda-recipe
# https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files

{% set version_match = load_file_regex(load_file="VERSION", regex_pattern='(\\d+\\.\\d+\\.\\d+)') %}
{% set version = version_match[1] %}

package:
  name: xmipp4-core
  version: {{ version }}

about:
  summary: Core library for the xmipp4 framework
  license_file: LICENSE

source:
  path: ../

build:
  number: 0
  script_env:
    - XMIPP4_CORE_BUILD_SPDLOG=OFF
  script:
    # Installation: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    # MSVC tools found in C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC
    #- pwd: /c/Miniconda/conda-bld/xmipp4-core_1751958195406/work
    # %RECIPE_DIR%: D:\a\xmipp4-core\xmipp4-core\conda
    
    # C++17 features marked as not available
    # https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    
    - echo "------------------- Start -------------------" # [win]
    - "powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File \"%RECIPE_DIR%\\visual-studio-name-detector.ps1\" > generator.txt"  # [win]
    - "set /p VS_GENERATOR=<generator.txt"  # [win]
    - set CMAKE_ARGS=%CMAKE_ARGS% -G "%VS_GENERATOR%"  # [win]
    - echo "------------------- End -------------------" # [win]
    
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --config-settings=cmake.args="%CMAKE_ARGS%"  # [win]
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation  # [not win]

requirements:
  run:
    - spdlog

  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake>=3.16
    - make # [unix]
    - spdlog

  host:
    - python
    - pip
    - scikit-build-core>=0.10
