name: "Detect OS type"
description: "Detects if OS is linux, macos, or windows"

inputs:
  os:
    description: "Specific OS the worker runs on"
    required: true

outputs:
  os_type:
    description: "Detected OS type"
    value: ${{ steps.detect-os-type.outputs.drmemory }}

runs:
  using: "composite"
  steps:
    - name: Detect OS type
      id: detect-os-type
      shell: bash
      run: |
        if [[ ${{ inputs.os }} == ubuntu* ]] ; then
          export OS_TYPE=debian
        elif [[ ${{ inputs.os }} == macos* ]] ; then
          export OS_TYPE=macos
        elif [[ ${{ inputs.os }} == windows* ]] ; then
          export OS_TYPE=windows
        else
          export OS_TYPE=unkown
        fi
        echo "os_type=$OS_TYPE" >> "$GITHUB_OUTPUT"
