name: "Generate Coverage Report"
description: "Generates coverage reports for every OS"

runs:
  using: "composite"
  steps:
    - name: Generate coverage report (Linux)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: |
        lcov --capture --directory . --output-file coverage.info --exclude '/usr/*'
        lcov --list coverage.info
        genhtml coverage.info --output-directory coverage_html

    - name: Generate coverage report (Windows)
      if: runner.os == 'Windows'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: |
        # For Windows with MSVC or gcc, we'll use a simpler approach
        echo "Coverage report generation for Windows requires additional setup"
        echo "Consider using OpenCppCoverage or gcovr for better results"
