name: "Generate Coverage Report"
description: "Generates coverage reports for every OS"

inputs:
  compiler-cc:
    description: "C compiler being used by the runner"
    required: true
  compiler-cxx:
    description: "C++ compiler being used by the runner"
    required: true
  cl-coverage-tool:
    description: "Path to the coverage tool used by Windows with MSVC"
    required: false
outputs:
  report-path:
    description: "Full path to the coverage report." 
    value: ${{ steps.generate-report.outputs.report-path }}

runs:
  using: "composite"
  steps:
    - name: Generate coverage report (GCC)
      if: inputs.compiler-cc == 'gcc' && inputs.compiler-cxx == 'g++'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      env:
        REPORT_PATH: ${{ github.workspace }}/build/coverage.xml
      run: |
        gcovr -r "${{ github.workspace }}" \
          --object-directory "${{ github.workspace }}/build" \
          --sonarqube -o "$REPORT_PATH" \
          --txt report.txt \
          --exclude '.*_deps/.*'
        cat report.txt

    - name: Generate coverage report (Clang)
      if: inputs.compiler-cc == 'clang' && inputs.compiler-cxx == 'clang++'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      env:
        REPORT_PATH: ${{ github.workspace }}/build/coverage.xml
      run: |
        gcovr -r "${{ github.workspace }}" \
          --object-directory "${{ github.workspace }}/build" \
          --gcov-executable "llvm-cov gcov" \
          --sonarqube -o "$REPORT_PATH" \
          --txt report.txt \
          --exclude '.*_deps/.*'
        cat report.txt

    - name: Generate coverage report (Windows)
      if: inputs.compiler-cc == 'cl' && inputs.compiler-cxx == 'cl' && inputs.cl-coverage-tool != ''
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      env:
        COVERAGE_EXECUTABLE: ${{ inputs.cl-coverage-tool }}
        REPORT_PATH: ${{ github.workspace }}/build/coverage.xml
      run: |
        "$COVERAGE_EXECUTABLE" \
          --export_type=cobertura \
          --output="$REPORT_PATH" \
          --sources="../src;../include" \
          -- ctest -C Debug \
          --output-on-failure 2>&1 | tee "${{ github.workspace }}/opencppcoverage.log"
        cat opencppcoverage.log

    - name: Return coverage report path
      id: generate-report
      shell: bash
      env:
        REPORT_PATH: ${{ github.workspace }}/build/coverage.xml
      run: echo "report-path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
