name: "Generate Coverage Report"
description: "Generates coverage reports for every OS."

inputs:
  compiler-c:
    description: "C compiler being used by the runner."
    required: true
  compiler-cxx:
    description: "C++ compiler being used by the runner."
    required: true
  cl-coverage-tool:
    description: "Path to the coverage tool used by Windows with MSVC."
    required: false
  report-path:
    description: "Path to save the coverage report."
    required: false
    default: "coverage.xml"

runs:
  using: "composite"
  steps:
    - name: Set gcov executable
      id: set-gcov-executable
      if: inputs.compiler-c != 'cl' && inputs.compiler-cxx != 'cl'
      shell: bash
      run: |
        if [[ "${{ inputs.compiler-c }}" == "clang" && "${{ inputs.compiler-cxx }}" == "clang++" ]]; then
          echo "gcov-executable=llvm-cov gcov" >> "$GITHUB_OUTPUT"
        else
          echo "gcov-executable=gcov" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate coverage report (all but MSVC)
      if: inputs.compiler-c != 'cl' && inputs.compiler-cxx != 'cl'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      run: |
        gcovr -r "${{ github.workspace }}" \
          --object-directory "${{ github.workspace }}/build" \
          --gcov-executable "${{ steps.set-gcov-executable.outputs.gcov-executable }}" \
          --cobertura -o "${{ inputs.report-path }}" \
          --exclude '.*_deps/.*'

    - name: Generate coverage report (Windows with MSVC)
      if: inputs.compiler-c == 'cl' && inputs.compiler-cxx == 'cl' && inputs.cl-coverage-tool != ''
      uses: gigabit-clowns/.github/.github/composites/run-ctest/internal@main
      with:
        test-wrapper: >-
          "${{ inputs.cl-coverage-tool }}" --working_dir="${{ github.workspace }}\build"
          --modules="xmipp4-core.dll"
          --sources="${{ github.workspace }}"
          --excluded_sources="*_deps*"
          --excluded_sources="*_work*"
          --export_type="cobertura:${{ inputs.report-path }}"
          --cover_children --

    - name: Show coverage summary
      shell: bash
      run: pycobertura show --format=text "${{ inputs.report-path }}"

    - name: Normalize report paths (all but MSVC)
      if: inputs.compiler-c != 'cl' && inputs.compiler-cxx != 'cl'
      shell: bash
      run: |
        # Replace workspace with placeholder for later unification
        ws=$(echo "$GITHUB_WORKSPACE" | sed 's|\\|/|g')
        sed -i.bak "s|$ws|GITHUB_WORKSPACE|g" "${{ inputs.report-path }}"
        rm -f "${{ inputs.report-path }}.bak"

    - name: Normalize report paths (Windows with MSVC)
      if: inputs.compiler-c == 'cl' && inputs.compiler-cxx == 'cl' && inputs.cl-coverage-tool != ''
      shell: bash
      run: |
        target="$GITHUB_WORKSPACE/msvc_path_normalization.py"
        url="https://raw.githubusercontent.com/gigabit-clowns/.github/main/.github/scripts/coverage/msvc_path_normalization.py"

        # Exit non-zero on HTTP errors
        curl -sSLo "$target" --fail "$url" || {
          echo "Failed to download $url"
          curl -sS -I "$url"
          exit 1
        }

        echo "Downloaded script to $target"
        python ./msvc_path_normalization.py "${{ inputs.report-path }}" --placeholder="GITHUB_WORKSPACE"
