name: "Generate Coverage Report"
description: "Generates coverage reports for every OS"

inputs:
  compiler-cc:
    description: "C compiler being used by the runner"
    required: true
  compiler-cxx:
    description: "C++ compiler being used by the runner"
    required: true
  cl-coverage-tool:
    description: "Path to the coverage tool used by Windows with MSVC"
    required: false
outputs:
  report-path:
    description: "Full path to the coverage report." 
    value: ${{ steps.generate-report.outputs.report-path }}

runs:
  using: "composite"
  steps:
    - name: Set gcov executable
      id: set-gcov-executable
      if: inputs.compiler-cc != 'cl' && inputs.compiler-cxx != 'cl'
      shell: bash
      run: |
        if [[ "${{ inputs.compiler-cc }}" == "clang" && "${{ inputs.compiler-cxx }}" == "clang++" ]]; then
          echo "gcov-executable=llvm-cov gcov" >> "$GITHUB_OUTPUT"
        else
          echo "gcov-executable=gcov" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate coverage report (Linux)
      if: inputs.compiler-cc != 'cl' && inputs.compiler-cxx != 'cl'
      working-directory: "${{ github.workspace }}/build"
      shell: bash
      env:
        REPORT_PATH: ${{ github.workspace }}/build/coverage.xml
      run: |
        gcovr -r "${{ github.workspace }}" \
          --object-directory "${{ github.workspace }}/build" \
          --gcov-executable "${{ steps.set-gcov-executable.outputs.gcov-executable }}" \
          --sonarqube -o "$REPORT_PATH" \
          --txt report.txt \
          --exclude '.*_deps/.*'
        cat report.txt

    #- name: Generate coverage report (Windows)
    #  if: inputs.compiler-cc == 'cl' && inputs.compiler-cxx == 'cl' && inputs.cl-coverage-tool != ''
    #  uses: ./.github/composites/run-ctest
    #  with:
    #    test-wrapper: '"${{ inputs.cl-coverage-tool }}" --export_type="cobertura:${{ github.workspace }}/build/coverage.xml" --sources="../src;../include" --'

    - name: Generate coverage report (Windows)
      if: inputs.compiler-cc == 'cl' && inputs.compiler-cxx == 'cl' && inputs.cl-coverage-tool != ''
      working-directory: "${{ github.workspace }}/build"
      shell: pwsh
      run: |
        $raw = '${{ inputs.cl-coverage-tool }}'
        Write-Host "Raw input path: $raw"
        
        # Show full command we will run (for copy/paste)
        $args = @(
          "--working_dir=${{ github.workspace }}\build",
          "--export_type=cobertura:${{ github.workspace }}\build\coverage.xml",
          "--sources=${{ github.workspace }}\src;${{ github.workspace }}\include",
          "--cover_children",
          "--",
          "ctest", "-C", $env:BUILD_TYPE, "-T", "test", "--rerun-failed", "--output-on-failure"
        )
        Write-Host "Command line:"
        Write-Host "& `"$tool`" $($args -join ' ')"
        
        Write-Host "`n=== Running OpenCppCoverage (verbose) ==="
        & "$tool" --verbose `
          --working_dir="${{ github.workspace }}\build" `
          --export_type="cobertura:${{ github.workspace }}\build\coverage.xml" `
          --sources="${{ github.workspace }}\src;${{ github.workspace }}\include" `
          --cover_children `
          --excluded_modules="C:\Windows\*" `
          -- ctest -C $env:BUILD_TYPE -T test --rerun-failed --output-on-failure 2>&1 | Tee-Object -Variable covout

        Write-Host "`n=== OpenCppCoverage exit output (last 200 lines) ==="
        $covout | Select-Object -Last 200 | ForEach-Object { Write-Host $_ }

        #& "${{ inputs.cl-coverage-tool }}" `
        #  --working_dir="${{ github.workspace }}" `
        #  --export_type="cobertura:${{ github.workspace }}/build/coverage.xml" `
        #  --sources="${{ github.workspace }}\src;${{ github.workspace }}\include" `
        #  -- ctest -C $env:BUILD_TYPE -T test --rerun-failed --output-on-failure

    - name: Return coverage report path
      id: generate-report
      shell: bash
      env:
        REPORT_PATH: ${{ github.workspace }}/build/coverage.xml
      run: echo "report-path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
