name: "Install Coverage tool"
description: "Installs the required coverage tool for every OS"

inputs:
  compiler-cc:
    description: "C compiler being used by the runner"
    required: true
  compiler-cxx:
    description: "C++ compiler being used by the runner"
    required: true
outputs:
  opencppcoverage:
    description: "Full path to OpenCppCoverage"
    value: ${{ steps.install-opencppcoverage.outputs.opencppcoverage }}

runs:
  using: "composite"
  steps:
    - name: Update (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if which apt; then
          sudo apt-get update
        else
          echo "Could not find a package manager for this system"
          exit 1
        fi

    - name: Install coverage tools (Linux - gcc -> gcov)
      if: runner.os == 'Linux' && (inputs.compiler-cc == 'gcc' || inputs.compiler-cxx == 'g++')
      shell: bash
      run: sudo apt-get install -y lcov

    - name: Install coverage tools (Linux - gcc -> llvm-cov)
      if: runner.os == 'Linux' && (inputs.compiler-cc == 'clang' || inputs.compiler-cxx == 'clang++')
      shell: bash
      run: sudo apt-get install -y llvm

    - name: Install coverage tools (macOS -> llvm-cov)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install llvm
        ln -s "$(brew --prefix llvm)/bin/llvm-cov" /usr/local/bin/llvm-cov || true

    - name: Install coverage tools (Windows -> OpenCppCoverage)
      id: install-opencppcoverage
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install OpenCppCoverage -y
        echo opencppcoverage="/c/Program Files/OpenCppCoverage/OpenCppCoverage.exe" >> "$GITHUB_OUTPUT"

    - name: Install gcovr
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install gcovr
