name: "Install Coverage tool"
description: "Installs the required coverage tool for every OS"

inputs:
  compiler-cc:
    description: "C compiler being used by the runner"
    required: true
  compiler-cxx:
    description: "C++ compiler being used by the runner"
    required: true
outputs:
  opencppcoverage-bash:
    description: "Full path to OpenCppCoverage (in bash format)"
    value: ${{ steps.install-opencppcoverage-bash.outputs.opencppcoverage }}
  opencppcoverage-pwsh:
    description: "Full path to OpenCppCoverage (in Powershell format)"
    value: ${{ steps.install-opencppcoverage-pwsh.outputs.opencppcoverage }}

runs:
  using: "composite"
  steps:
    - name: Update (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if which apt; then
          sudo apt-get update
        else
          echo "This system is not supported as it does not use apt"
          exit 1
        fi

    - name: Install coverage tools (Linux - gcc -> gcov)
      if: runner.os == 'Linux' && inputs.compiler-cc == 'gcc' && inputs.compiler-cxx == 'g++'
      shell: bash
      run: sudo apt-get install -y lcov

    - name: Install coverage tools (Linux - gcc -> llvm-cov)
      if: runner.os == 'Linux' && inputs.compiler-cc == 'clang' && inputs.compiler-cxx == 'clang++'
      shell: bash
      run: sudo apt-get install -y llvm

    - name: Install coverage tools (macOS -> llvm-cov)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install llvm
        ln -s "$(brew --prefix llvm)/bin/llvm-cov" /usr/local/bin/llvm-cov || true

    - name: Install gcovr (GCC & clang)
      if: inputs.compiler-cc != 'cl' && inputs.compiler-cxx != 'cl'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install gcovr

    - name: Install coverage tools (Windows -> OpenCppCoverage)
      id: install-opencppcoverage-bash
      if: inputs.compiler-cc == 'cl' && inputs.compiler-cxx == 'cl'
      shell: bash
      run: |
        choco install OpenCppCoverage -y
        echo opencppcoverage="/c/Program Files/OpenCppCoverage/OpenCppCoverage.exe" >> "$GITHUB_OUTPUT"

    - name: Export OpenCppCoverage path (Powershell)
      id: install-opencppcoverage-pwsh
      if: inputs.compiler-cc == 'cl' && inputs.compiler-cxx == 'cl'
      shell: pwsh
      run: |
        $path = 'C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe'
        Add-Content -Path $env:GITHUB_OUTPUT -Value "opencppcoverage-windows=$path"
