target_sources(
	rexlib-unitary-tests
	PRIVATE
		test_caching_image_reader_provider.cpp
		test_direct_image_reader_provider.cpp
		test_image_format_registration.cpp
		test_image_location.cpp
		test_image_metadata.cpp
		test_image_probe.cpp
		test_image_read_format_manager.cpp
		test_image_region_grouping.cpp
		test_image_sink.cpp
		test_image_source.cpp
		test_image_transaction_plan.cpp
		test_image_transfer_plan.cpp
		test_image_write_format_manager.cpp
		test_index_table.cpp
		test_interned_path_list.cpp
		test_managed_image_writer_provider.cpp
)

add_subdirectory(formats)
