// SPDX-License-Identifier: GPL-3.0-only

#ifndef XMIPP4_SMALL_AXIS_COUNT
	#define XMIPP4_SMALL_AXIS_COUNT 8UL
#endif

#ifndef XMIPP4_SMALL_OPERAND_COUNT
	#define XMIPP4_SMALL_OPERAND_COUNT 8UL
#endif

#ifndef XMIPP4_SMALL_QUEUE_COUNT
	#define XMIPP4_SMALL_QUEUE_COUNT 16UL
#endif

#ifndef XMIPP4_SMALL_OUTPUT_OPERAND_COUNT
	#define XMIPP4_SMALL_OUTPUT_OPERAND_COUNT 4UL
#endif

#ifndef XMIPP4_SMALL_INPUT_OPERAND_COUNT
	#define XMIPP4_SMALL_INPUT_OPERAND_COUNT 16UL
#endif

#ifndef XMIPP4_SMALL_SCRATCH_OPERAND_COUNT
	#define XMIPP4_SMALL_SCRATCH_OPERAND_COUNT 2UL
#endif

#ifndef XMIPP4_DEFAULT_OPERATION_COMMAND_CACHE_CAPACITY
	#define XMIPP4_DEFAULT_OPERATION_COMMAND_CACHE_CAPACITY 256UL
#endif
