// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include <complex>
#include <cstdint>

#include <hwy/highway.h>

#define XMIPP4_HWY_CHAR8_SUFFIX C8
#define XMIPP4_HWY_UINT8_SUFFIX U8
#define XMIPP4_HWY_INT8_SUFFIX I8
#define XMIPP4_HWY_UINT16_SUFFIX U16
#define XMIPP4_HWY_INT16_SUFFIX I16
#define XMIPP4_HWY_UINT32_SUFFIX U32
#define XMIPP4_HWY_INT32_SUFFIX I32
#define XMIPP4_HWY_UINT64_SUFFIX U64
#define XMIPP4_HWY_INT64_SUFFIX I64
#define XMIPP4_HWY_FLOAT16_SUFFIX F16
#define XMIPP4_HWY_FLOAT32_SUFFIX F32
#define XMIPP4_HWY_FLOAT64_SUFFIX F64
#define XMIPP4_HWY_COMPLEX32_SUFFIX C32
#define XMIPP4_HWY_COMPLEX64_SUFFIX C64
#define XMIPP4_HWY_COMPLEX128_SUFFIX C128



#define XMIPP4_HWY_FOR_EACH_UNSIGNED_INTEGER_TYPE(F) \
	F(uint8_t, U8) \
	F(uint16_t, U16) \
	F(uint32_t, U32) \
	F(uint64_t, U64)

#define XMIPP4_HWY_FOR_EACH_SIGNED_INTEGER_TYPE(F) \
	F(int8_t, I8) \
	F(int16_t, I16) \
	F(int32_t, I32) \
	F(int64_t, I64)

#define XMIPP4_HWY_FOR_EACH_INTEGER_TYPE(F) \
	XMIPP4_HWY_FOR_EACH_UNSIGNED_INTEGER_TYPE(F) \
	XMIPP4_HWY_FOR_EACH_SIGNED_INTEGER_TYPE(F)

// TODO add F16
#define XMIPP4_HWY_FOR_EACH_FLOATING_TYPE(F) \
	F(hwy::float16_t, F16) \
	F(hwy::float32_t, F32) \
	F(hwy::float64_t, F64)

// TODO add C32
#define XMIPP4_HWY_FOR_EACH_COMPLEX_TYPE(F) \
	F(std::complex<hwy::float16_t>, C32) \
	F(std::complex<hwy::float32_t>, C64) \
	F(std::complex<hwy::float64_t>, C128)

#define XMIPP4_HWY_FOR_EACH_ARITHMETIC_TYPE(F) \
	XMIPP4_HWY_FOR_EACH_INTEGER_TYPE(F) \
	XMIPP4_HWY_FOR_EACH_FLOATING_TYPE(F) \
	XMIPP4_HWY_FOR_EACH_COMPLEX_TYPE(F)
