#***************************************************************************
# Authors:     Oier Lauzirika Zarrabeitia (oierlauzi@bizkaia.eu)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307  USA
#
#  All comments concerning this program package may be sent to the
#  e-mail address 'xmipp@cnb.csic.es'
# ***************************************************************************

# File based on:
# https://github.com/pybind/cmake_example/blob/master/conda.recipe/meta.yaml
# https://scikit-build-core.readthedocs.io/en/stable/faqs.html#making-a-conda-recipe

package:
  name: xmipp4-core
  version: "0.1.0"

about:
  summary: Core library for the xmipp4 framework
  license_file: LICENSE

source:
  path: ../

build:
  number: 0
  script_env:
  script:
    # C++17 features marked as not available
    # https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  run:
    - spdlog

  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake>=3.16
    - make # [unix]
    - spdlog

  host:
    - python
    - pip
    - scikit-build-core>=0.10
