name: Build and Test with pip

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  pip-build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04
        - macos-latest
        - windows-latest
  
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xmipp4-core with pip
        run: pip install . -v

      # TODO run tests
