#***************************************************************************
# Authors:     Oier Lauzirika Zarrabeitia (oierlauzi@bizkaia.eu)
#              Martín Salinas Antón (ssalinasmartin@gmail.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307  USA
#
#  All comments concerning this program package may be sent to the
#  e-mail address 'xmipp@cnb.csic.es'
# ***************************************************************************

name: Build wheels and source distribution

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }} ${{ matrix.architectures }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            architectures: "x86_64 i686 aarch64 ppc64le s390x"
            use_qemu: true
          - os: macos-latest
            architectures: "x86_64 arm64 universal2"
            use_qemu: false
          - os: windows-latest
            architectures: "AMD64 x86 ARM64"
            use_qemu: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.use_qemu == 'true'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_ARCHS: "${{ matrix.architectures }}"
          CIBW_BUILD: "cp39-*" # Python agnostic
    
      - name: List wheels
        run: ls -l ./wheelhouse
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  # TODO add here the distribution job
