name: Build and Test with pip

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python:
        - '3.10'
  
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install xmipp4-core with pip
        run: pip install . -vvv

      # TODO run tests
