name: Build
on:
  pull_request:
    branches: [devel, master]
jobs:
  build:
    # Configuration matrix
    strategy:
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Configure the project
        uses: threeal/cmake-action@v1.2.0

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build


  