name: Build and Test with conda

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # - windows-latest # FIXME
        python:
        - '3.10'
  
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          conda-solver: "classic"
          activate-environment: "" # Base is required for conda-build

      - name: Install conda-build and conda-verify
        run: conda install -y conda-build conda-verify

      - name: Build with conda
        run: conda-build conda.recipe --python=${{ matrix.python }}

      # TODO run tests