name: Generate new release

on:
  workflow_dispatch:

jobs:
  tag_and_release:
    name: Generate new tag & GitHub release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check authorisation level of dispatching user
      uses: ./.github/composites/authorize-user
      with:
        allowed_roles: "admin maintain"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Retrieve tag name, release name & changelog
      id: variables
      uses: ./.github/composites/release-variables
    
    - name: Generate tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.variables.outputs.TAG_NAME }}
        tag_prefix: ''
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.variables.outputs.RELEASE_NAME }}
        body: ${{ steps.variables.outputs.CHANGELOG_BODY }}
